// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (license !== "None") {
    return `![Badge](https://img.shields.io/badge/License-${license}-blue.svg)`;
  } else return ``;
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  //  Defining variables that hold licenses and their links
  let license = `${data.license}`;
  let link = "";

  // Assigning the correct link to the license
  if (license === "MIT License") {
    license = "MIT";
    link = "https://choosealicense.com/licenses/mit/";
  }

  if (license === "GNU AGPLv3") {
    license = "GNU AGPLv3";
    link = "https://choosealicense.com/licenses/agpl-3.0/";
  }

  if (license === "GNU GPLv3") {
    license = "GNU GPLv3";
    link = "https://choosealicense.com/licenses/gpl-3.0/";
  }

  if (license === "GNU LGPLv3") {
    license = "GNU LGPLv3";
    link = "https://choosealicense.com/licenses/lgpl-3.0/";
  }

  if (license === "Apache License 2.0") {
    license = "Apache License 2.0";
    link = "https://choosealicense.com/licenses/apache-2.0/";
  }

  if (license === "Mozilla Public License 2.0") {
    license = "Mozilla Public License 2.0";
    link = "https://choosealicense.com/licenses/mpl-2.0/";
  }

  if (license === "CDDL-1.0") {
    license = "CDDL-1.0";
    link = "https://opensource.org/licenses/CDDL-1.0";
  }

  // Assigning the correct link to the license

  if (license !== "None") {
    return `![Badge](https://img.shields.io/badge/License-${license}-blue.svg)`;
  } else return ``;
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if (license !== "None") {
    return `## License
        License details for this application can be found at ${license}`;
  } else return ``;
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}

    ${renderLicenseBadge(data.license)}
    ## Description
    ${data.description}

    ## Table of Content
    - [Instalation](#instailation)
    - [Usage](#usage)
    ${renderLicenseLink(data.license)}
    - [Contributing](#contributing)
    - [Test](#Test)
    - [Questions](#questions)
    
    ## Instalation
    ${data.installation}
    ## Usage
    ${data.usage}
    ${renderLicenseSection(data.license)}
    ## Contributing
    ${data.contributing}
    ## Test
    ${data.test}
    ## Questions
    I am available at the following email address if you have any questions: ${
      data.email
    }

    Here is my GitHub account:  [${data.username}](https://github.com/${
    data.username
  })

    ---
    _This README has been generated by ❤  [Professional-README-generator]( https://github.com/ghashe/professional-README-generator) © 2022_  
  `;
}

module.exports = generateMarkdown;
